### ISSUE TITLE
Python 3.11

### ISSUE THREAD

**Issue by AiyionPrime** [mpnordland/agua_amiga#1]
Hey there, I'd like to use you projects but am currently struggling building it on my python 3.11 running machine.

I hope I did not miss anything, but I installed python 3.10 in parallel, setup a venv running on 3.10 accordingly, installed pyinstaller in there and ran the steps from the Makefile in that order.

The application does work? when I then install the built wheel in the venv and run `agua_amiga`.
At least the UI does.

Whether the bluetooth part works, I cannot tell yet, as it does not find my bottle.
Before I start debugging that, are there any technical reasons, why this project is limited to 3.10 and not 3.11?
I'd really like to use the system python instead of the venv.

**Comment by mpnordland** [comment]
Uh, well, none that I remember. That may have been setup by poetry. I'll try and see if it works on 3.11 now.

**Comment by mpnordland** [comment]
So looks like that was due to how pyinstaller specifies its dependencies. I've updated them but it's not currently working on my own system rn but I suspect that may be for other reasons. I'll dig into this further after work this evening.

**Comment by mpnordland** [comment]
I pushed my changes so far in case you find that helpful.

**Comment by AiyionPrime** [comment]
That was fast, thanks :D
I'm just digging into trouble-shooting my bottle.
It's a hidratespark pro, and as far as I can tell (just getting started with `gatttool`) at least the sip-uuid is still present; so maybe this tool works just fine, after I got past setting the bottle up initially.

**Comment by mpnordland** [comment]
Yeah I had no other bottles to test with so I have no idea if it will work. I gathered most of my knowledge on how the protocol works from https://github.com/choonkiatlee/wban-python/blob/master/Hidrate.py#L152 which is sparse on details as well. A really great way to explore your device is with [d-feet](https://wiki.gnome.org/Apps/DFeet) and the BlueZ dbus service. Bonus thing is that this is also how agua amiga talks to bluetooth devices so you see the same things it sees.

**Comment by mpnordland** [comment]
Hmm agua amiga uses python-dbus-next and there's an error that happens on Python 3.11 in that library. A fix was merged but a new release is not forth coming. I'm going to try building/running it from git to see if that fixes the segfault. I'm pretty sure it's in that library because I've tracked the failure to the line that connects to DBus.

**Comment by AiyionPrime** [comment]
Not sure if that helps, but this is an strace for the latest commit.
https://aiyionpri.me/shared/agua_amiga/ea9af4d1.strace

**Comment by AiyionPrime** [comment]
You mean https://github.com/altdesktop/python-dbus-next/issues/138, right?

**Comment by mpnordland** [comment]
Yeah that's the one. Using master branch from that git repo fixes the segfault on my end so I've pushed updates to the dependencies.

**Comment by AiyionPrime** [comment]
Confirmed; the latest commit builds without problems.

**Comment by mpnordland** [comment]
Sweet! I'll close this issue then but feel free to open another if you run into more problems.
